version: 1
jobs:
  build:
    working_directory: ~/community-portal

    docker:
      - image: circleci/node:10.3

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "./functions/package.json" }}
            - dependencies-cachep

      - run:
          name: Install dependencies
          command: |
            sudo npm i -g serverless
            cd functions
            npm install
        
      - run:
          name: run tests
          command: |
            cd functions

      - run:
          name: deploy application
          command: |
            cd functions
            if ["${CIRCLE_BRANCH}" == "staging"] then
              sls deploy --stage staging;
            elif ["${CIRCLE_BRANCH}" == "master"] then
              sls deploy --state prod;
            else 
              sls deploy --state dev;
            fi
            
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "./functions/package.json" }}

