authorization:
    name: ${self:provider.stage}-authorization
    role: authorizationRole
    handler: handlers/authorization/handler.handler
    events:
    - http:
        path: /authorize/
        method: post
        cors: true