getTeam:
  name: ${self:provider.stage}-getTeam
  role: getTeamRole
  handler: handlers/partners/getTeam/handler.handler
  events:
  - http:
      path: /partners/team/{id}
      method: get
      cors: true,
      request:
        parameters:
          paths:
            id: true
