custom:
  dynamodb:
    start:
      migrate: true
  functions:
    public: # update later
      - getProjectCards
      - updateProjectStatus
      - getProjectDetails
      - getToken
      - projects
      - users
      - likeProject

provider:
  name: aws
  runtime: nodejs8.10
  stage: {$opt:stage, 'dev'}
  region: us-east-1
  environment:
    PROJECTS_TABLE: community-portal-projects
    PROJECTS_INDEX: community-portal-projects-status-upvotes-index
    USERS_TABLE: community-portal-users
    TAGS_TABLE: community-portal-tags
    SKILLS_TABLE: community-portal-skills
    JWT_SECRET: Cg9UCqAlMNImL2tIgQPBoUlxL5PjHQGFg5pTujilUbE5IYqU31M5uLiYlk2TB3b
    JWT_EXPIRATION_TIME: 5m

package:
  individually: false
  exclude:
    - coverage/**
    - .circleci/**

service: test-endpoint

functions:
  - ${file(./handlers/authorizer/authorizer.yml)}
  - ${file(./handlers/project/create/createProject/createProject.yml)}
  - ${file(./handlers/project/get/getProjectCards/getProjectCards.yml)}
  - ${file(./handlers/project/get/getProjectDetails/getProjectDetails.yml)}
  - ${file(./handlers/project/update/updateProjectStatus/updateProjectStatus.yml)}
  - ${file(./handlers/project/projects/projects.yml)}
  - ${file(./handlers/token/get/get.yml)}
  - ${file(./handlers/user/users/users.yml)}
  - ${file(./handlers/user/update/likeProject/likeProject.yml)}

# Add references to defined tables and roles here before deployment
resources:
  Resources:
    ProjectsTable: ${file(./schema.json):Projects}
    UsersTable: ${file(./schema.json):Users}
    TagsTable: ${file(./schema.json):Tags}
    SkillsTable: ${file(./schema.json):Skills}
    createProjectRole: ${file(./handlers/project/create/createProject/role.yml):createProjectRole}
    getProjectCardsRole: ${file(./handlers/project/get/getProjectCards/role.yml):getProjectCardsRole}
    getProjectDetailsRole: ${file(./handlers/project/get/getProjectDetails/role.yml):getProjectDetailsRole}
    updateProjectStatusRole: ${file(./handlers/project/update/updateProjectStatus/role.yml):updateProjectStatusRole}
    likeProjectRole: ${file(./handlers/user/update/likeProject/role.yml):likeProjectRole}

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline # serverless-offline needs to be last in the list
