custom:
  jwt:
    secret: ${env:JWT_SECRET}
    expiration_time: 20d
  github:
    client_id: ${self:provider.github_client_id} # github auth app client_id
    client_secret: ${self:provider.github_client_secret} # github auth app client_secret
  dynamodb:
    start:
      migrate: true
  functions:
    # Add lambda functions for public endpoints here so Jest will not complain
    public:
      - authorization
      - getProjectCards
      - getProjectDetails
  domainNames:
    dev:
      name: dev.api.opensource.engcom.magento.com
      path: ${opt:branch, ''}
      stage: ${opt:stage, ''}
    staging:
      name: api.opensource.engcom.magento.com
      path: ${opt:branch, ''}
      stage: ${opt:stage, ''}
    production:
      name: api.opensource.magento.com
      path: ${opt:branch, ''}
      stage: ${opt:stage, ''}
  customDomain:
   domainName: ${self:custom.domainNames.${opt:stage, 'dev'}.name}
   basePath: ${self:custom.domainNames.${opt:stage, 'dev'}.path} # If created by CircleCI prefix will correspond to the branch code is pushed to
   stage: ${self:provider.stage} # Stage will be created for every branch
   createRoute53Record: false

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.domainNames.${opt:stage, 'dev'}.stage, 'dev'}
  github_client_id: ${env:GITHUB_CLIENT_ID}
  github_client_secret: ${env:GITHUB_CLIENT_SECRET}
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    PROJECTS_TABLE: ${file(./schema.json):Projects.Properties.TableName}
    PROJECTS_INDEX: ${file(./schema.json):Projects.Properties.TableName}-index
    USERS_TABLE: ${file(./schema.json):Users.Properties.TableName}
    USERS_INDEX: ${file(./schema.json):Users.Properties.TableName}-index
    TAGS_TABLE: ${file(./schema.json):Tags.Properties.TableName}
    SKILLS_TABLE: ${file(./schema.json):Skills.Properties.TableName}
    PULL_REQUESTS_TABLE: ${file(./schema.json):PullRequests.Properties.TableName}
    PULL_REQUESTS_INDEX: ${file(./schema.json):PullRequests.Properties.TableName}-index
    EPICS_TABLE: ${file(./schema.json):Epics.Properties.TableName}
    EPICS_INDEX: ${file(./schema.json):Epics.Properties.TableName}-index
    ISSUES_TABLE: ${file(./schema.json):Issues.Properties.TableName}
    ISSUES_INDEX: ${file(./schema.json):Issues.Properties.TableName}-index
    JWT_SECRET: ${self:custom.jwt.secret}
    JWT_EXPIRATION_TIME: ${self:custom.jwt.expiration_time}
    BASE_PATH: ${self:custom.domainNames.${opt:stage, 'dev'}.path}
    GITHUB_CLIENT_ID: ${self:custom.github.client_id}
    GITHUB_CLIENT_SECRET: ${self:custom.github.client_secret}
  iamRoleStatements:
      - Effect: Allow
        Action:
          - logs:*
        Resource:
          - 'Fn::Join':
            - ':'
            -
              - 'arn:aws:logs'
              - '*'
              - '*'
              - '*'
      - Effect: Allow
        Action:
          - cloudwatch:*
          - logs:*
        Resource:
          - '*'
package:
  individually: false
  exclude:
    - coverage/**
    - .circleci/**

service: community-portal

functions:
  - ${file(./handlers/authorizer/authorizer.yml)}
  - ${file(./handlers/authorization/authorization.yml)}
  - ${file(./handlers/project/createProject/createProject.yml)}
  - ${file(./handlers/project/getProjectCards/getProjectCards.yml)}
  - ${file(./handlers/project/getProjectDetails/getProjectDetails.yml)}
  - ${file(./handlers/project/editProject/editProject.yml)}
  - ${file(./handlers/project/updateProjectStatus/updateProjectStatus.yml)}
  - ${file(./handlers/user/likeProject/likeProject.yml)}
  - ${file(./handlers/user/bookmarkProject/bookmarkProject.yml)}
  - ${file(./handlers/user/unlikeProject/unlikeProject.yml)}
  - ${file(./handlers/user/getLikedProjects/getLikedProjects.yml)}
  - ${file(./handlers/user/getBookmarkedProjects/getBookmarkedProjects.yml)}
  - ${file(./handlers/user/pledge/pledge.yml)}

resources:
  Resources:
    # Allow CORS headers for custom authorizer
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
        ResponseTemplates:
          application/json: "{\"error\": $context.error.messageString}"
    # Add references to defined tables and roles here before deployment
    ProjectsTable: ${file(./schema.json):Projects}
    UsersTable: ${file(./schema.json):Users}
    TagsTable: ${file(./schema.json):Tags}
    SkillsTable: ${file(./schema.json):Skills}
    PullRequestsTable: ${file(./schema.json):PullRequests}
    EpicsTable: ${file(./schema.json):Epics}
    IssuesTable: ${file(./schema.json):Issues}
    createProjectRole: ${file(./handlers/project/createProject/role.yml):createProjectRole}
    getProjectCardsRole: ${file(./handlers/project/getProjectCards/role.yml):getProjectCardsRole}
    getProjectDetailsRole: ${file(./handlers/project/getProjectDetails/role.yml):getProjectDetailsRole}
    editProjectRole: ${file(./handlers/project/editProject/role.yml):editProjectRole}
    updateProjectStatusRole: ${file(./handlers/project/updateProjectStatus/role.yml):updateProjectStatusRole}
    likeProjectRole: ${file(./handlers/user/likeProject/role.yml):likeProjectRole}
    bookmarkProjectRole: ${file(./handlers/user/bookmarkProject/role.yml):bookmarkProjectRole}
    unlikeProjectRole: ${file(./handlers/user/unlikeProject/role.yml):unlikeProjectRole}
    getLikedProjectsRole: ${file(./handlers/user/getLikedProjects/role.yml):getLikedProjectsRole}
    getBookmarkedProjectsRole: ${file(./handlers/user/getBookmarkedProjects/role.yml):getBookmarkedProjectsRole}
    pledgeRole: ${file(./handlers/user/pledge/role.yml):pledgeRole}
    authorizationRole: ${file(./handlers/authorization/role.yml):authorizationRole}

plugins:
  - serverless-domain-manager
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline # serverless-offline needs to be last in the list
