provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

package:
  individually: true
  exclude:
    - coverage/**
    - .circleci/**

service: test-endpoint

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

functions:
  - ${file(./handlers/projects/projects.yml)}
  - ${file(./handlers/users/users.yml)}