custom:
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: {$opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - lambda:InvokeFunction
        - lambda:InvokeAsync
        - lambda:GetFunction
        - lambda:CreateFunction
        - lambda:deleteFunction
        - lambda:updateFunctionCode
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/community-portal-test"
  environment:
    TEST_TABLE: community-portal-test
    JWT_SECRET: Cg9UCqAlMNImL2tIgQPBoUlxL5PjHQGFg5pTujilUbE5IYqU31M5uLiYlk2TB3b
    JWT_EXPIRATION_TIME: 5m

package:
  individually: false
  exclude:
    - coverage/**
    - .circleci/**

service: test-endpoint

functions:
  - ${file(./handlers/read/projects/projects.yml)}
  - ${file(./handlers/read/users/users.yml)}
  - ${file(./handlers/read/getProject/getProject.yml)}
  - ${file(./handlers/create/createProject/createProject.yml)}
  - ${file(./handlers/authorize/getToken/getToken.yml)}

resources:
  Resources:
    ${file(./schema.json)}

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline #serverless-offline needs to be last in the list
