custom:
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: {$opt:stage, 'dev'}
  region: us-east-1
  environment:
    PROJECTS_TABLE: community-portal-projects
    PROJECTS_INDEX: community-portal-projects-status-upvotes-index
    USERS_TABLE: community-portal-users
    TAGS_TABLE: community-portal-tags
    SKILLS_TABLE: community-portal-skills
    JWT_SECRET: Cg9UCqAlMNImL2tIgQPBoUlxL5PjHQGFg5pTujilUbE5IYqU31M5uLiYlk2TB3b
    JWT_EXPIRATION_TIME: 5m

package:
  individually: false
  exclude:
    - coverage/**
    - .circleci/**

service: test-endpoint

functions:
  - ${file(./handlers/authorizer/authorizer.yml)}
  - ${file(./handlers/project/create/create.yml)}
  - ${file(./handlers/project/getProjectCards/getProjectCards.yml)}
  - ${file(./handlers/project/get/get.yml)}
  - ${file(./handlers/project/projects/projects.yml)}
  - ${file(./handlers/token/get/get.yml)}
  - ${file(./handlers/user/users/users.yml)}
  - ${file(./handlers/user/likeProject/likeProject.yml)}

# Add references to defined tables and roles here before deployment
resources:
  Resources:
    ProjectsTable: ${file(./schema.json):Projects}
    UsersTable: ${file(./schema.json):Users}
    TagsTable: ${file(./schema.json):Tags}
    SkillsTable: ${file(./schema.json):Skills}
    getProjectCardsRole: ${file(./handlers/project/getProjectCards/role.yml):getProjectCardsRole}
    getProjectRole: ${file(./handlers/project/get/role.yml):getProjectRole}
    createProjectRole: ${file(./handlers/project/create/role.yml):createProjectRole}
    likeProjectRole: ${file(./handlers/user/likeProject/role.yml):likeProjectRole}

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline # serverless-offline needs to be last in the list
