likeProject:
  name: ${self:provider.stage}-likeProject
  role: likeProjectRole
  handler: handlers/user/likeProject/handler.handler
  timeout: 10
  events:
  - http:
      path: /user/likeProject
      method: post
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
