updateProjectStatus:
  role: updateProjectStatusRole
  handler: handlers/project/update/updateProjectStatus/handler.handler
  events:
  - http:
      path: /project/status
      method: put
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
