getTeams:
  name: ${self:provider.stage}-getTeams
  role: getTeamsRole
  handler: handlers/partners/getTeams/handler.handler
  events:
  - http:
      path: /partners/teams/
      method: get
      cors: true
