editProject:
  role: editProjectRole
  handler: handlers/project/update/editProject/handler.handler
  events:
  - http:
      path: /project/edit
      method: post
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
