version: 1
jobs:
  build:
    working_directory: ~/community-portal/functions

    docker:
      - image: circleci/node:10.3

    steps:
      - checkout:
          path: ~/community-portal/

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "./package.json" }}
            - dependencies-cache
      
      - run:    
          name: Install Java
          command: 'sudo apt-get update && sudo apt-get install default-jre default-jdk'

      - run:
          name: setup container
          command: |
            curl -k -L -o dynamodb-local.tgz http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
            tar -xzf dynamodb-local.tgz
            java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb

      - run:
          name: Install dependencies
          command: npm install
        
      - run:
          name: Setup Local DynamoDB
          command: node_modules/.bin/sls offline start

      - run:
          name: run tests
          command: npm test

      - run:
          name: deploy application
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              node_modules/.bin/sls deploy --stage staging
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              node_modules/.bin/sls deploy --stage prod
            else  
              node_modules/.bin/sls deploy --stage dev
            fi
          
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "./package.json" }}

