getProjectDetails:
  name: ${self:provider.stage}-getProjectDetails
  role: getProjectDetailsRole
  handler: handlers/project/getProjectDetails/handler.handler
  events:
  - http:
      path: /project/{id}
      method: get
      cors: true
      request:
        parameters:
          paths:
            id: true
