getProjectDetails:
  name: ${self:provider.stage}-getProjectDetails
  role: getProjectDetailsRole
  handler: handlers/project/getProjectDetails/handler.handler
  events:
  - http:
      path: /project/{project_id}
      method: get
      cors: true
      authorizer:
        name: extractor
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
      request:
        parameters:
          paths:
            project_id: true
