getProjectDetails:
  name: ${self:provider.stage}-getProjectDetails
  role: ${self:provider.stage}-getProjectDetailsRole
  handler: handlers/project/getProjectDetails/handler.handler
  events:
  - http:
      path: /project/{project_id}
      method: get
      cors: true
      request:
        parameters:
          paths:
            project_id: true
