editProject:
  name: ${self:provider.stage}-editProject
  role: ${self:provider.stage}-editProjectRole
  handler: handlers/project/editProject/handler.handler
  events:
  - http:
      path: /project
      method: put
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
