read:
    handler: handlers/read/getProject/handler.handler
    events:
    - http:
        path: /project/{projectId}
        method: get
        cors: true
        request:
            parameters:
              paths:
                projectId: true
