pledge:
  name: ${self:provider.stage}-pledge
  role: pledgeRole
  handler: handlers/user/pledge/handler.handler
  timeout: 10
  events:
  - http:
      path: /user/pledge
      method: post
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
