getUserInfo:
  name: ${self:provider.stage}-getUserInfo
  role: getUserInfoRole
  handler: handlers/user/getUserInfo/handler.handler
  timeout: 10
  events:
  - http:
      path: /user/{id}
      method: get
      cors: true
