postGithubData:
  name: ${self:provider.stage}-postGithubData
  role: postGithubDataRole
  handler: handlers/user/postGithubData/handler.handler
  timeout: 10
  events:
  - http:
      path: /user/github
      method: post
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
