joinProject:
  name: ${self:provider.stage}-joinProject
  role: joinProjectRole
  handler: handlers/project/joinProject/handler.handler
  events:
  - http:
      path: /project/join
      method: post
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
