unlikeProject:
  name: ${self:provider.stage}-unlikeProject
  role: unlikeProjectRole
  handler: handlers/user/unlikeProject/handler.handler
  timeout: 10
  events:
  - http:
      path: /user/unlikeProject
      method: post
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
