unbookmarkProject:
  name: ${self:provider.stage}-unbookmarkProject
  role: unbookmarkProjectRole
  handler: handlers/user/unbookmarkProject/handler.handler
  timeout: 10
  events:
  - http:
      path: /user/bookmarkProject
      method: delete
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
