getBookmarkedProjects:
  name: ${self:provider.stage}-getBookmarkedProjects
  role: getBookmarkedProjectsRole
  handler: handlers/user/getBookmarkedProjects/handler.handler
  timeout: 10
  events:
  - http:
      path: /user/bookmarkedProjects
      method: get
      cors: true
      authorizer:
        name: authorizer
        resultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
        identityValidationExpression: .*
        type: token
