getProjectDetails:
  role: getProjectDetailsRole
  handler: handlers/project/get/getProjectDetails/handler.handler
  events:
  - http:
      path: /project/{project_id}
      method: get
      cors: true
      request:
        parameters:
          paths:
            project_id: true
